# Generated by Django 4.0.4 on 2022-06-03 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_user_profile_pic_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.CharField(choices=[('default0', 'default0'), ('default1', 'default1'), ('default2', 'default2'), ('default3', 'default3'), ('default4', 'default4'), ('default5', 'default5')], default='default3', max_length=12),
        ),
        migrations.AlterField(
            model_name='user',
            name='theme',
            field=models.CharField(choices=[('dark', 'dark'), ('dark-yellow', 'dark-yellow'), ('dark-purple', 'dark-purple'), ('dark-red', 'dark-red'), ('dark-gray', 'dark-gray'), ('light', 'light'), ('light-yellow', 'light-yellow'), ('light-purple', 'light-purple'), ('light-red', 'light-red'), ('light-black', 'light-black')], default='light', max_length=12),
        ),
    ]
